#!/bin/sh
export PATH=/usr/local/bin:$PATH

script_dir=$(dirname $0)
cd $script_dir
cd ..

echo >&2 "###PRE-COMMIT###".

pkg_chg=`git diff --name-only --cached --exit-code package.json`

if [ -n "$pkg_chg" ]
then
  echo >&2 "Unbundling linked packages".

  # Stash unstaged changes
  git stash -q --keep-index

  # Revert package
  node ./tools/unbundle-packages.js

  # Stage updated files
  git add -u

  # Re-apply original unstaged changes
  git stash pop -q
fi

echo >&2 "###END PRE-COMMIT###".
